name: Build App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ecr_repository: [cats, web, dogs]  # 여러 개의 ECR 리포지토리 지정

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Check Node version
        run: node -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # AWS_REGION은 Secrets로 관리

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get image tag (version)
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.ecr_repository }}  # 매트릭스 사용
          IMAGE_TAG: ${{ steps.image.outputs.version }}
        run: |
            echo "::set-output name=ecr_repository::$ECR_REPOSITORY"
            echo "::set-output name=image_tag::$IMAGE_TAG"
            echo "Pushing image to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./$ECR_REPOSITORY
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USERNAME }}/k8s-manifest-repo
          ref: main
          token: \${{ secrets.ACTION_TOKEN }}
          path: k8s-manifest-repo

      - name: Update Kubernetes resources
        run: |
            cd k8s-manifest-repo/base/
            kustomize edit set image \
            058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/cats=058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/cats:${{ steps.image.outputs.image_tag }} \
            058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/dogs=058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/dogs:${{ steps.image.outputs.image_tag }} \
            058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/web=058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/web:${{ steps.image.outputs.image_tag }}

      - name: Commit files
        run: |
            cd k8s-manifest-repo
            git config --global user.email "github-actions@github.com"
            git config --global user.name "github-actions"
            git commit -am "Update image tag"
            git push -u origin main
